<?php
session_start();
session_register("sbjbs_username");
session_register("sbjbs_userid");
session_register("sbjbs_memtype");
session_register("sbjbs_emp_username");
session_register("sbjbs_emp_userid");
//session_register("sbjbs_emp_username");
//session_register("sbjbs_emp_userid");
session_register("softbiz_jbs_provided");
//session_register("ID");
//session_register("ID");
?>